import { AdminUser as User } from '../users/types';

export interface TikrarTahfidz {
  id: string;
  user_id: string;
  batch_id: string;
  program_id: string;
  understands_commitment: boolean;
  tried_simulation: boolean;
  no_negotiation: boolean;
  has_telegram: boolean;
  saved_contact: boolean;
  has_permission: boolean;
  permission_name?: string;
  permission_phone?: string;
  chosen_juz?: string;
  no_travel_plans: boolean;
  motivation?: string;
  ready_for_team?: string;
  full_name?: string;
  address?: string;
  wa_phone?: string;
  telegram_phone?: string;
  birth_date?: string;
  age?: number;
  domicile?: string;
  timezone?: string;
  main_time_slot?: string;
  backup_time_slot?: string;
  time_commitment: boolean;
  understands_program: boolean;
  questions?: string;
  batch_name?: string;
  submission_date: string;
  status: string;
  selection_status: string;
  approved_by?: string;
  approved_at?: string;
  oral_submitted_at?: string;
  oral_submission_url?: string | null;
  oral_submission_file_name?: string | null;
  oral_makhraj_errors?: number;
  oral_sifat_errors?: number;
  oral_mad_errors?: number;
  oral_ghunnah_errors?: number;
  oral_harakat_errors?: number;
  oral_total_score?: number;
  oral_assessment_status?: string;
  oral_assessed_by?: string;
  oral_assessed_at?: string;
  oral_assessment_notes?: string;
  alasan_mengundurkan_diri?: string;
  written_quiz_score?: number;
  written_quiz_total_questions?: number;
  written_quiz_correct_answers?: number;
  written_quiz_submitted_at?: string;
  written_exam_submitted_at?: string;
  written_exam_status?: string;
  exam_score?: number;
  exam_submitted_at?: string;
  exam_status?: string;
  exam_juz_number?: number;
  user?: User;
  batch?: { name: string };
  program?: { name: string };
}

export interface TikrarStatsData {
  total: number;
  pending: number;
  approved: number;
  rejected: number;
  withdrawn: number;
  completed: number;
  selectionPending: number;
  selectionApproved: number;
  selectionRejected: number;
  oralSubmitted: number;
  writtenSubmitted: number;
  bothTestsSubmitted: number;
}
