-- Create activity_logs table for audit trail
-- Run this in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS public.activity_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  action VARCHAR(100) NOT NULL,
  resource VARCHAR(100) NOT NULL,
  details JSONB,
  ip_address INET,
  user_agent TEXT,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  level VARCHAR(10) CHECK (level IN ('INFO', 'WARN', 'ERROR')) NOT NULL
);

-- Create indexes for better query performance
CREATE INDEX idx_activity_logs_user_id ON public.activity_logs(user_id);
CREATE INDEX idx_activity_logs_timestamp ON public.activity_logs(timestamp DESC);
CREATE INDEX idx_activity_logs_action_resource ON public.activity_logs(action, resource);
CREATE INDEX idx_activity_logs_level ON public.activity_logs(level);
CREATE INDEX idx_activity_logs_ip_address ON public.activity_logs(ip_address);

-- Create error_logs table for error tracking
CREATE TABLE IF NOT EXISTS public.error_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message TEXT NOT NULL,
  stack TEXT,
  context JSONB,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  resolved BOOLEAN DEFAULT FALSE,
  resolved_at TIMESTAMP WITH TIME ZONE,
  resolved_by UUID REFERENCES auth.users(id)
);

-- Create indexes for error_logs
CREATE INDEX idx_error_logs_timestamp ON public.error_logs(timestamp DESC);
CREATE INDEX idx_error_logs_resolved ON public.error_logs(resolved);

-- Create audit_log_retention function for cleanup
CREATE OR REPLACE FUNCTION cleanup_old_logs()
RETURNS void AS $$
BEGIN
  -- Delete activity logs older than 1 year
  DELETE FROM public.activity_logs
  WHERE timestamp < NOW() - INTERVAL '1 year';

  -- Delete resolved error logs older than 6 months
  DELETE FROM public.error_logs
  WHERE resolved = TRUE
  AND resolved_at IS NOT NULL
  AND resolved_at < NOW() - INTERVAL '6 months';

  RAISE NOTICE 'Old logs cleaned up successfully';
END;
$$ LANGUAGE plpgsql;

-- Create a scheduled job to run cleanup monthly (if using Supabase cron)
-- Uncomment the line below if you have cron extension enabled
-- SELECT cron.schedule('cleanup-logs', '0 0 1 * *', 'SELECT cleanup_old_logs();');

-- Grant permissions
GRANT SELECT, INSERT ON public.activity_logs TO authenticated;
GRANT SELECT, INSERT ON public.error_logs TO authenticated;
GRANT UPDATE ON public.error_logs TO authenticated;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO authenticated;

-- Create RLS policies
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.error_logs ENABLE ROW LEVEL SECURITY;

-- Policy for activity_logs
-- Users can only see their own logs, admins can see all
CREATE POLICY "Users can view own activity logs" ON public.activity_logs
  FOR SELECT
  USING (
    auth.uid() = user_id OR
    EXISTS (
      SELECT 1 FROM public.users
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

CREATE POLICY "Users can insert own activity logs" ON public.activity_logs
  FOR INSERT
  WITH CHECK (true);

-- Policy for error_logs
CREATE POLICY "Admins can view all error logs" ON public.error_logs
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.users
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

CREATE POLICY "Admins can manage error logs" ON public.error_logs
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.users
      WHERE id = auth.uid() AND role = 'admin'
    )
  );