BEGIN;
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('c69b0312-e765-4e50-9747-44af48dc0bc5', 1, 'A', 1, 'Ketentuan Ujian', 1, 'multiple_choice', 'Bismillah.. Apakah habibaty siap mengerjakan soal Ujian Akhir Juz 1A dengan jujur karena Allah tanpa melihat Al Quran, HP, Google atau nanya ke teman, saudara, Mama, Papa, chat GPT, Gemini, Siri atau siapapun yang akan membuat hasil dari ujian muroja''ah ini tidak valid?Perlu diketahui hasil ujian bukanlah ajang tinggi-tinggian nilai, yang dapat nilai Mumtaz Murtafi juga ga akan mendapat hadiah apapun dari  ataupun Akademi, tapi ini sangat berarti buat kami untuk memperbaiki kekurangan program  pada angkatan yang akan datang.Kisi-kisi soal1. Sambung ayat2. Tebak HalamanTafaddhol, silakan muroja''ah terlebih dahulu..Kami serahkan persaksian kejujuran menjawab soal-soal ini kepada Allah Asy- Syahid yang Maha Menyaksikan.Semoga Allah mudahkan, Baarakallahu Fiikunn"Tak ada gading yang tak retak."Jika antum menemukan kesalahan dalam kunci jawaban atau pengetikan, silakan japri Kak Mara melalui WA di: 0813-1365-0842🚩TANBIH Protes kesalahan kunci jawaban hanya jika antunna punya bukti Screenshot saja, setelah selesai submit dan cek Al Quran. Mohon maaf kami tidak melayani protes saat mengerjakan soal atau setelah mengerjakan soal tanpa bukti kesalahan kami.', '["Bismillah saya siap dan paham semua ketentuan di atas"]'::jsonb, 'Bismillah saya siap dan paham semua ketentuan di atas', true, 0);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('1a17d5d4-07ba-4c55-b671-3619bf951dcc', 1, 'A', 1, 'Lanjutkan potongan ayat', 2, 'multiple_choice', 'ٱلَّذِينَ يُؤْمِنُونَ بِٱلْغَيْبِ وَيُقِيمُونَ ٱلصَّلَوٰةَ وَمِمَّا رَزَقْنَٰهُمْ يُنفِقُونَ', '["ٱلَّذِينَ يُؤْمِنُونَ بِمَآ أُنزِلَ إِلَيْكَ وَمَآ أُنزِلَ مِن قَبْلِكَ وَبِٱلءَاخِرَةِ هُمْ يُوقِنُونَ","وَٱلَّذِينَ يُؤْمِنُونَ بِمَآ أُنزِلَ إِلَيْكَ وَمَآ أُنزِلَ مِن قَبْلِكَ وَبِٱلْءَاخِرَةِ هُمْ يُوقِنُونَ"]'::jsonb, 'ٱلَّذِينَ يُؤْمِنُونَ بِمَآ أُنزِلَ إِلَيْكَ وَمَآ أُنزِلَ مِن قَبْلِكَ وَبِٱلءَاخِرَةِ هُمْ يُوقِنُونَ', true, 2);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('86602cde-b101-4e64-8d52-b0e95c9ab4a9', 1, 'A', 1, 'Lanjutkan potongan ayat', 3, 'multiple_choice', 'أُو۟لَٰٓئِكَ عَلَىٰ هُدًى مِّن رَّبِّهِمْ ۖ وَأُو۟لَٰٓئِكَ هُمُ ٱلْمُفْلِحُونَ', '["وَٱلَّذِينَ كَفَرُوا۟ سَوَآءٌ عَلَيْهِمْ ءَأَنذَرْتَهُمْ أَمْ لَمْ تُنذِرْهُمْ لَا يُؤْمِنُونَ","إِنَّ ٱلَّذِينَ كَفَرُوا۟ سَوَآءٌ عَلَيْهِمْ ءَأَنذَرْتَهُمْ أَمْ لَمْ تُنذِرْهُمْ لَا يُؤْمِنُونَ"]'::jsonb, 'وَٱلَّذِينَ كَفَرُوا۟ سَوَآءٌ عَلَيْهِمْ ءَأَنذَرْتَهُمْ أَمْ لَمْ تُنذِرْهُمْ لَا يُؤْمِنُونَ', true, 2);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('c4cc70da-67bc-46cd-8e37-fe3ed6506c17', 1, 'A', 1, 'Lanjutkan potongan ayat', 4, 'multiple_choice', 'وَبَشِّرِ ٱلَّذِينَ ءَامَنُوا۟ وَعَمِلُوا۟ ٱلصَّٰلِحَٰتِ أَنَّ لَهُمْ جَنَّٰتٍ تَجْرِى مِن تَحْتِهَا ٱلْأَنْهَٰرُ ۖ كُلَّمَا رُزِقُوا۟ مِنْهَا مِن ثَمَرَةٍ رِّزْقًا ۙ قَالُوا۟ هَٰذَا ٱلَّذِى رُزِقْنَا مِن قَبْلُ ۖ وَأُتُوا۟ بِهِۦ مُتَشَٰبِهًا ۖ وَلَهُمْ فِيهَآ أَزْوَٰجٌ مُّطَهَّرَةٌ ۖ وَهُمْ فِيهَا خَٰلِدُونَ', '["كَيْفَ تَكْفُرُونَ بِٱللَّهِ وَكُنتُمْ أَمْوَٰتًا فَأَحْيَٰكُمْ ۖ ثُمَّ يُمِيتُكُمْ ثُمَّ يُحْيِيكُمْ ثُمَّ إِلَيْهِ تُرْجَعُونَ","إِنَّ ٱللَّهَ لَا يَسْتَحْىِۦٓ أَن يَضْرِبَ مَثَلًا مَّا بَعُوضَةً فَمَا فَوْقَهَا ۚ فَأَمَّا ٱلَّذِينَ ءَامَنُوا۟ فَيَعْلَمُونَ أَنَّهُ ٱلْحَقُّ مِن رَّبِّهِمْ ۖ وَأَمَّا ٱلَّذِينَ كَفَرُوا۟ فَيَقُولُونَ مَاذَآ أَرَادَ ٱللَّهُ بِهَٰذَا مَثَلًا ۘ يُضِلُّ بِهِۦ كَثِيرًا وَيَهْدِى بِهِۦ كَثِيرًا ۚ وَمَا يُضِلُّ بِهِۦٓ إِلَّا ٱلْفَٰسِقِينَ","كَيْفَ تَكْفُرُونَ بِٱللَّهِ وَكُنتُمْ أَمْوَٰتًا فَأَحْيَٰكُمْ ۖ ثُمَّ يُمِيتُكُمْ ثُمَّ يُحْيِيكُمْ ثُمَّ إِلَيْهِ تُرْجَعُونَ"]'::jsonb, 'كَيْفَ تَكْفُرُونَ بِٱللَّهِ وَكُنتُمْ أَمْوَٰتًا فَأَحْيَٰكُمْ ۖ ثُمَّ يُمِيتُكُمْ ثُمَّ يُحْيِيكُمْ ثُمَّ إِلَيْهِ تُرْجَعُونَ', true, 2);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('f7a5afed-5bfb-472f-8047-ab60f2c3c300', 1, 'A', 1, 'Lanjutkan potongan ayat', 5, 'multiple_choice', 'فَأَزَلَّهُمَا ٱلشَّيْطَٰنُ عَنْهَا فَأَخْرَجَهُمَا مِمَّا كَانَا فِيهِ ۖ وَقُلْنَا ٱهْبِطُوا۟ بَعْضُكُمْ لِبَعْضٍ عَدُوٌّ ۖ وَلَكُمْ فِى ٱلْأَرْضِ مُسْتَقَرٌّ وَمَتَٰعٌ إِلَىٰ حِينٍ', '["فَتَلَقَّىٰٓ ءَادَمُ مِن رَّبِّهِۦ كَلِمَٰتٍ فَتَابَ عَلَيْهِ ۚ إِنَّهُۥ هُوَ ٱلتَّوَّابُ ٱلرَّحِيمُ","فَتَلَقَّىٰٓ ءَادَمُ مِن رَّبِّهِمْ كَلِمَٰتٍ فَتَابَ عَلَيْهِ ۚ إِنَّهُۥ هُوَ ٱلتَّوَّابُ ٱلرَّحِيمُ"]'::jsonb, 'فَتَلَقَّىٰٓ ءَادَمُ مِن رَّبِّهِۦ كَلِمَٰتٍ فَتَابَ عَلَيْهِ ۚ إِنَّهُۥ هُوَ ٱلتَّوَّابُ ٱلرَّحِيمُ', true, 2);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('3f4c2186-ae1d-4297-acd1-157a945aa328', 1, 'A', 1, 'Lanjutkan potongan ayat', 6, 'multiple_choice', 'قُلْنَا ٱهْبِطُوا۟ مِنْهَا جَمِيعًا ۖ فَإِمَّا يَأْتِيَنَّكُم مِّنِّى هُدًى فَمَن تَبِعَ هُدَاىَ فَلَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ', '["وَءَامِنُوا۟ بِمَآ أَنزَلْتُ مُصَدِّقًا لِّمَا مَعَكُمْ وَلَا تَكُونُوٓا۟ أَوَّلَ كَافِرٍۭ بِهِۦ ۖ وَلَا تَشْتَرُوا۟ بِـَٔايَٰتِى ثَمَنًا قَلِيلًا وَإِيَّٰىَ فَٱتَّقُونِ","وَٱلَّذِينَ كَفَرُوا۟ وَكَذَّبُوا۟ بِـَٔايَٰتِنَآ أُو۟لَٰٓئِكَ أَصْحَٰبُ ٱلنَّارِ ۖ هُمْ فِيهَا خَٰلِدُونَ"]'::jsonb, 'وَءَامِنُوا۟ بِمَآ أَنزَلْتُ مُصَدِّقًا لِّمَا مَعَكُمْ وَلَا تَكُونُوٓا۟ أَوَّلَ كَافِرٍۭ بِهِۦ ۖ وَلَا تَشْتَرُوا۟ بِـَٔايَٰتِى ثَمَنًا قَلِيلًا وَإِيَّٰىَ فَٱتَّقُونِ', true, 2);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('874bd767-1ea2-40e4-9977-27a4522bd4ad', 1, 'A', 1, 'Lanjutkan potongan ayat', 7, 'multiple_choice', 'وَءَامِنُوا۟ بِمَآ أَنزَلْتُ مُصَدِّقًا لِّمَا مَعَكُمْ وَلَا تَكُونُوٓا۟ أَوَّلَ كَافِرٍۭ بِهِۦ ۖ وَلَا تَشْتَرُوا۟ بِـَٔايَٰتِى ثَمَنًا قَلِيلًا وَإِيَّٰىَ فَٱتَّقُونِ', '["وَلَا تَلْبِسُوا۟ ٱلْحَقَّ بِٱلْبَٰطِلِ وَتَكْتُمُوا۟ ٱلْحَقَّ وَأَنتُمْ تَعْلَمُونَ","وَٱلَّذِينَ كَفَرُوا۟ وَكَذَّبُوا۟ بِـَٔايَٰتِنَآ أُو۟لَٰٓئِكَ أَصْحَٰبُ ٱلنَّارِ ۖ هُمْ فِيهَا خَٰلِدُونَ"]'::jsonb, 'وَلَا تَلْبِسُوا۟ ٱلْحَقَّ بِٱلْبَٰطِلِ وَتَكْتُمُوا۟ ٱلْحَقَّ وَأَنتُمْ تَعْلَمُونَ', true, 2);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('40cf32f3-a424-43d2-a580-07e148d85a14', 1, 'A', 1, 'Lanjutkan potongan ayat', 8, 'multiple_choice', 'وَإِذْ وَٰعَدْنَا مُوسَىٰٓ أَرْبَعِينَ لَيْلَةً ثُمَّ ٱتَّخَذْتُمُ ٱلْعِجْلَ مِنۢ بَعْدِهِۦ وَأَنتُمْ ظَٰلِمُونَ', '["ثُمَّ عَفَوْنَا عَنكُم مِّنۢ بَعْدِ ذَٰلِكَ لَعَلَّكُمْ تَشْكُرُونَ","ثُمَّ بَعَثْنَٰكُم مِّنۢ بَعْدِ مَوْتِكُمْ لَعَلَّكُمْ تَشْكُرُونَ"]'::jsonb, 'ثُمَّ عَفَوْنَا عَنكُم مِّنۢ بَعْدِ ذَٰلِكَ لَعَلَّكُمْ تَشْكُرُونَ', true, 2);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('374c7018-edc8-4a17-8a2d-3a710929e0c5', 1, 'A', 1, 'Lanjutkan potongan ayat', 9, 'multiple_choice', 'وَٱلَّذِينَ كَفَرُوا۟ وَكَذَّبُوا۟ بِـَٔايَٰتِنَآ أُو۟لَٰٓئِكَ أَصْحَٰبُ ٱلنَّارِ ۖ هُمْ فِيهَا خَٰلِدُونَ', '["يَٰبَنِىٓ إِسْرَٰٓءِيلَ ٱذْكُرُوا۟ نِعْمَتِىَ ٱلَّتِىٓ أَنْعَمْتُ عَلَيْكُمْ وَأَوْفُوا۟ بِعَهْدِىٓ أُوفِ بِعَهْدِكُمْ وَإِيَّٰىَ فَٱرْهَبُونِ","يَٰبَنِىٓ إِسْرَٰٓءِيلَ ٱذْكُرُوا۟ نِعْمَتِىَ ٱلَّتِىٓ أَنْعَمْتُ عَلَيْكُمْ وَأَنِّى فَضَّلْتُكُمْ عَلَى ٱلْعَٰلَمِينَ"]'::jsonb, 'يَٰبَنِىٓ إِسْرَٰٓءِيلَ ٱذْكُرُوا۟ نِعْمَتِىَ ٱلَّتِىٓ أَنْعَمْتُ عَلَيْكُمْ وَأَوْفُوا۟ بِعَهْدِىٓ أُوفِ بِعَهْدِكُمْ وَإِيَّٰىَ فَٱرْهَبُونِ', true, 2);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('8bd02507-8444-4e8f-8eb7-b0d418b107e7', 1, 'A', 1, 'Lanjutkan potongan ayat', 10, 'multiple_choice', 'يَٰبَنِىٓ إِسْرَٰٓءِيلَ ٱذْكُرُوا۟ نِعْمَتِىَ ٱلَّتِىٓ أَنْعَمْتُ عَلَيْكُمْ وَأَنِّى فَضَّلْتُكُمْ عَلَى ٱلْعَٰلَمِينَ', '["وَءَامِنُوا۟ بِمَآ أَنزَلْتُ مُصَدِّقًا لِّمَا مَعَكُمْ وَلَا تَكُونُوٓا۟ أَوَّلَ كَافِرٍۭ بِهِۦ ۖ وَلَا تَشْتَرُوا۟ بِـَٔايَٰتِى ثَمَنًا قَلِيلًا وَإِيَّٰىَ فَٱتَّقُونِ","وَٱتَّقُوا۟ يَوْمًا لَّا تَجْزِى نَفْسٌ عَن نَّفْسٍ شَيْـًٔا وَلَا يُقْبَلُ مِنْهَا شَفَٰعَةٌ وَلَا يُؤْخَذُ مِنْهَا عَدْلٌ وَلَا هُمْ يُنصَرُونَ"]'::jsonb, 'وَءَامِنُوا۟ بِمَآ أَنزَلْتُ مُصَدِّقًا لِّمَا مَعَكُمْ وَلَا تَكُونُوٓا۟ أَوَّلَ كَافِرٍۭ بِهِۦ ۖ وَلَا تَشْتَرُوا۟ بِـَٔايَٰتِى ثَمَنًا قَلِيلًا وَإِيَّٰىَ فَٱتَّقُونِ', true, 2);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('ad348bab-0ed5-42a8-a8b3-f2b1603578b2', 1, 'A', 1, 'Lanjutkan potongan ayat', 11, 'multiple_choice', 'وَإِذَا قِيلَ لَهُمْ لَا تُفْسِدُوا۟ فِى ٱلْأَرْضِ قَالُوٓا۟ إِنَّمَا نَحْنُ مُصْلِحُونَ', '["أَلَآ إِنَّهُمْ هُمُ ٱلسُّفَهَآءُ وَلَٰكِن لَّا يَعْلَمُونَ","أَلَآ إِنَّهُمْ هُمُ ٱلْمُفْسِدُونَ وَلَٰكِن لَّا يَشْعُرُونَ"]'::jsonb, 'أَلَآ إِنَّهُمْ هُمُ ٱلسُّفَهَآءُ وَلَٰكِن لَّا يَعْلَمُونَ', true, 2);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('7a33a530-c120-4d9b-aa43-2f6bf13bf511', 1, 'A', 1, 'Lanjutkan potongan ayat', 12, 'multiple_choice', 'وَإِذَا قِيلَ لَهُمْ ءَامِنُوا۟ كَمَآ ءَامَنَ ٱلنَّاسُ قَالُوٓا۟ أَنُؤْمِنُ كَمَآ ءَامَنَ ٱلسُّفَهَآءُ', '["أَلَآ إِنَّهُمْ هُمُ ٱلسُّفَهَآءُ وَلَٰكِن لَّا يَعْلَمُونَ","أَلَآ إِنَّهُمْ هُمُ ٱلْمُفْسِدُونَ وَلَٰكِن لَّا يَشْعُرُونَ"]'::jsonb, 'أَلَآ إِنَّهُمْ هُمُ ٱلسُّفَهَآءُ وَلَٰكِن لَّا يَعْلَمُونَ', true, 2);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('416766c3-e606-4c43-bd67-97510903dddd', 1, 'A', 1, 'Lanjutkan potongan ayat', 13, 'multiple_choice', 'فِى قُلُوبِهِم مَّرَضٌ فَزَادَهُمُ ٱللَّهُ مَرَضًا ۖ وَلَهُمْ عَذَابٌ أَلِيمٌۢ بِمَا كَانُوا۟ يَكْذِبُونَ', '["وَإِذَا قِيلَ لَهُمْ لَا تُفْسِدُوا۟ فِى ٱلْأَرْضِ قَالُوٓا۟ إِنَّمَا نَحْنُ مُصْلِحُونَ","وَإِذَا قِيلَ لَهُمْ ءَامِنُوا۟ كَمَآ ءَامَنَ ٱلنَّاسُ قَالُوٓا۟ أَنُؤْمِنُ كَمَآ ءَامَنَ ٱلسُّفَهَآءُ"]'::jsonb, 'وَإِذَا قِيلَ لَهُمْ لَا تُفْسِدُوا۟ فِى ٱلْأَرْضِ قَالُوٓا۟ إِنَّمَا نَحْنُ مُصْلِحُونَ', true, 2);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('577510bf-1f28-49f5-94e7-99da88bf678a', 1, 'A', 1, 'Lanjutkan potongan ayat', 14, 'multiple_choice', 'ٱللَّهُ يَسْتَهْزِئُ بِهِمْ وَيَمُدُّهُمْ فِى طُغْيَٰنِهِمْ يَعْمَهُونَ', '["أُو۟لَٰٓئِكَ ٱلَّذِينَ ٱشْتَرَوُا۟ ٱلضَّلَٰلَةَ بِٱلْهُدَىٰ فَمَا رَبِحَت تِّجَٰرَتُهُمْ وَمَا كَانُوا۟ مُهْتَدِينَ","أَوْ كَصَيِّبٍ مِّنَ ٱلسَّمَآءِ فِيهِ ظُلُمَٰتٌ وَرَعْدٌ وَبَرْقٌ يَجْعَلُونَ أَصَٰبِعَهُمْ فِىٓ ءَاذَانِهِم مِّنَ ٱلصَّوَٰعِقِ حَذَرَ ٱلْمَوْتِ ۚ وَٱللَّهُ مُحِيطٌۢ بِٱلْكَٰفِرِينَ"]'::jsonb, 'أُو۟لَٰٓئِكَ ٱلَّذِينَ ٱشْتَرَوُا۟ ٱلضَّلَٰلَةَ بِٱلْهُدَىٰ فَمَا رَبِحَت تِّجَٰرَتُهُمْ وَمَا كَانُوا۟ مُهْتَدِينَ', true, 2);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('6e8a41bc-0674-4ac2-a9c8-fd64217d1a6d', 1, 'A', 1, 'Lanjutkan potongan ayat', 15, 'multiple_choice', 'يَٰٓأَيُّهَا ٱلنَّاسُ ٱعْبُدُوا۟ رَبَّكُمُ ٱلَّذِى خَلَقَكُمْ وَٱلَّذِينَ مِن قَبْلِكُمْ لَعَلَّكُمْ تَتَّقُونَ', '["فِى قُلُوبِهِم مَّرَضٌ فَزَادَهُمُ ٱللَّهُ مَرَضًا ۖ وَلَهُمْ عَذَابٌ أَلِيمٌۢ بِمَا كَانُوا۟ يَكْذِبُونَ","ٱلَّذِى جَعَلَ لَكُمُ ٱلْأَرْضَ فِرَٰشًا وَٱلسَّمَآءَ بِنَآءً وَأَنزَلَ مِنَ ٱلسَّمَآءِ مَآءً فَأَخْرَجَ بِهِۦ مِنَ ٱلثَّمَرَٰتِ رِزْقًا لَّكُمْ ۖ فَلَا تَجْعَلُوا۟ لِلَّهِ أَندَادًا وَأَنتُمْ تَعْلَمُونَ"]'::jsonb, 'فِى قُلُوبِهِم مَّرَضٌ فَزَادَهُمُ ٱللَّهُ مَرَضًا ۖ وَلَهُمْ عَذَابٌ أَلِيمٌۢ بِمَا كَانُوا۟ يَكْذِبُونَ', true, 2);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('871b4464-34d6-4c46-9244-7437f2ee6d85', 1, 'A', 1, 'Lanjutkan potongan ayat', 16, 'multiple_choice', 'أَوَلَا يَعْلَمُونَ أَنَّ ٱللَّهَ يَعْلَمُ مَا يُسِرُّونَ وَمَا يُعْلِنُونَ', '["فَوَيْلٌ لِّلَّذِينَ يَكْتُبُونَ ٱلْكِتَٰبَ بِأَيْدِيهِمْ ثُمَّ يَقُولُونَ هَٰذَا مِنْ عِندِ ٱللَّهِ لِيَشْتَرُوا۟ بِهِۦ ثَمَنًا قَلِيلًا ۖ فَوَيْلٌ لَّهُم مِّمَّا كَتَبَتْ أَيْدِيهِمْ وَوَيْلٌ لَّهُم مِّمَّا يَكْسِبُونَ","وَمِنْهُمْ أُمِّيُّونَ لَا يَعْلَمُونَ ٱلْكِتَٰبَ إِلَّآ أَمَانِىَّ وَإِنْ هُمْ إِلَّا يَظُنُّونَ"]'::jsonb, 'فَوَيْلٌ لِّلَّذِينَ يَكْتُبُونَ ٱلْكِتَٰبَ بِأَيْدِيهِمْ ثُمَّ يَقُولُونَ هَٰذَا مِنْ عِندِ ٱللَّهِ لِيَشْتَرُوا۟ بِهِۦ ثَمَنًا قَلِيلًا ۖ فَوَيْلٌ لَّهُم مِّمَّا كَتَبَتْ أَيْدِيهِمْ وَوَيْلٌ لَّهُم مِّمَّا يَكْسِبُونَ', true, 2);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('18caaf2b-2165-42f6-a98e-c3583bf754c2', 1, 'A', 1, 'Lanjutkan potongan ayat', 17, 'multiple_choice', 'وَٱلَّذِينَ ءَامَنُوا۟ وَعَمِلُوا۟ ٱلصَّٰلِحَٰتِ أُو۟لَٰٓئِكَ أَصْحَٰبُ ٱلْجَنَّةِ ۖ هُمْ فِيهَا خَٰلِدُونَ', '["وَإِذْ أَخَذْنَا مِيثَٰقَكُمْ وَرَفَعْنَا فَوْقَكُمُ ٱلطُّورَ خُذُوا۟ مَآ ءَاتَيْنَٰكُم بِقُوَّةٍ وَٱسْمَعُوا۟ ۖ قَالُوا۟ سَمِعْنَا وَعَصَيْنَا وَأُشْرِبُوا۟ فِى قُلُوبِهِمُ ٱلْعِجْلَ بِكُفْرِهِمْ ۚ قُلْ بِئْسَمَا يَأْمُرُكُم بِهِۦٓ إِيمَٰنُكُمْ إِن كُنتُم مُّؤْمِنِينَ","وَإِذْ أَخَذْنَا مِيثَٰقَ بَنِىٓ إِسْرَٰٓءِيلَ لَا تَعْبُدُونَ إِلَّا ٱللَّهَ وَبِٱلْوَٰلِدَيْنِ إِحْسَانًا وَذِى ٱلْقُرْبَىٰ وَٱلْيَتَٰمَىٰ وَٱلْمَسَٰكِينِ وَقُولُوا۟ لِلنَّاسِ حُسْنًا وَأَقِيمُوا۟ ٱلصَّلَوٰةَ وَءَاتُوا۟ ٱلزَّكَوٰةَ ثُمَّ تَوَلَّيْتُمْ إِلَّا قَلِيلًا مِّنكُمْ وَأَنتُم مُّعْرِضُونَ"]'::jsonb, 'وَإِذْ أَخَذْنَا مِيثَٰقَكُمْ وَرَفَعْنَا فَوْقَكُمُ ٱلطُّورَ خُذُوا۟ مَآ ءَاتَيْنَٰكُم بِقُوَّةٍ وَٱسْمَعُوا۟ ۖ قَالُوا۟ سَمِعْنَا وَعَصَيْنَا وَأُشْرِبُوا۟ فِى قُلُوبِهِمُ ٱلْعِجْلَ بِكُفْرِهِمْ ۚ قُلْ بِئْسَمَا يَأْمُرُكُم بِهِۦٓ إِيمَٰنُكُمْ إِن كُنتُم مُّؤْمِنِينَ', true, 2);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('a9126b6b-00e0-4cd7-9afc-2614f044fd0e', 1, 'A', 1, 'Lanjutkan potongan ayat', 18, 'multiple_choice', 'فَقُلْنَا ٱضْرِبُوهُ بِبَعْضِهَا ۚ كَذَٰلِكَ يُحْىِ ٱللَّهُ ٱلْمَوْتَىٰ وَيُرِيكُمْ ءَايَٰتِهِۦ لَعَلَّكُمْ تَعْقِلُونَ', '["ثُمَّ قَسَتْ قُلُوبُكُم مِّنۢ بَعْدِ ذَٰلِكَ فَهِىَ كَٱلْحِجَارَةِ أَوْ أَشَدُّ قَسْوَةً ۚ وَإِنَّ مِنَ ٱلْحِجَارَةِ لَمَا يَتَفَجَّرُ مِنْهُ ٱلْأَنْهَٰرُ ۚ وَإِنَّ مِنْهَا لَمَا يَشَّقَّقُ فَيَخْرُجُ مِنْهُ ٱلْمَآءُ ۚ وَإِنَّ مِنْهَا لَمَا يَهْبِطُ مِنْ خَشْيَةِ ٱللَّهِ ۗ وَمَا ٱللَّهُ بِغَٰفِلٍ عَمَّا تَعْمَلُونَ","أَفَتَطْمَعُونَ أَن يُؤْمِنُوا۟ لَكُمْ وَقَدْ كَانَ فَرِيقٌ مِّنْهُمْ يَسْمَعُونَ كَلَٰمَ ٱللَّهِ ثُمَّ يُحَرِّفُونَهُۥ مِنۢ بَعْدِ مَا عَقَلُوهُ وَهُمْ يَعْلَمُونَ"]'::jsonb, 'ثُمَّ قَسَتْ قُلُوبُكُم مِّنۢ بَعْدِ ذَٰلِكَ فَهِىَ كَٱلْحِجَارَةِ أَوْ أَشَدُّ قَسْوَةً ۚ وَإِنَّ مِنَ ٱلْحِجَارَةِ لَمَا يَتَفَجَّرُ مِنْهُ ٱلْأَنْهَٰرُ ۚ وَإِنَّ مِنْهَا لَمَا يَشَّقَّقُ فَيَخْرُجُ مِنْهُ ٱلْمَآءُ ۚ وَإِنَّ مِنْهَا لَمَا يَهْبِطُ مِنْ خَشْيَةِ ٱللَّهِ ۗ وَمَا ٱللَّهُ بِغَٰفِلٍ عَمَّا تَعْمَلُونَ', true, 2);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('1a66049e-2188-453b-8d5a-0d7f4769fc6b', 1, 'A', 1, 'Lanjutkan potongan ayat', 19, 'multiple_choice', 'وَإِذَا لَقُوا۟ ٱلَّذِينَ ءَامَنُوا۟ قَالُوٓا۟ ءَامَنَّا وَإِذَا خَلَا بَعْضُهُمْ إِلَىٰ بَعْضٍ قَالُوٓا۟ أَتُحَدِّثُونَهُم بِمَا فَتَحَ ٱللَّهُ عَلَيْكُمْ لِيُحَآجُّوكُم بِهِۦ عِندَ رَبِّكُمْ ۚ أَفَلَا تَعْقِلُونَ', '["أَوَلَا يَعْلَمُونَ أَنَّ ٱللَّهَ يَعْلَمُ مَا يُسِرُّونَ وَمَا يُعْلِنُونَ","إِنَّ ٱلَّذِينَ ءَامَنُوا۟ وَٱلَّذِينَ هَادُوا۟ وَٱلنَّصَٰرَىٰ وَٱلصَّٰبِـِٔينَ مَنْ ءَامَنَ بِٱللَّهِ وَٱلْيَوْمِ ٱلْءَاخِرِ وَعَمِلَ صَٰلِحًا فَلَهُمْ أَجْرُهُمْ عِندَ رَبِّهِمْ وَلَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ"]'::jsonb, 'أَوَلَا يَعْلَمُونَ أَنَّ ٱللَّهَ يَعْلَمُ مَا يُسِرُّونَ وَمَا يُعْلِنُونَ', true, 2);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('6b3d0d92-23e2-4f48-8a4c-a87bb0402f3c', 1, 'A', 1, 'Lanjutkan potongan ayat', 20, 'multiple_choice', 'وَإِذْ فَرَقْنَا بِكُمُ ٱلْبَحْرَ فَأَنجَيْنَٰكُمْ وَأَغْرَقْنَآ ءَالَ فِرْعَوْنَ وَأَنتُمْ تَنظُرُونَ', '["وَإِذْ وَٰعَدْنَا مُوسَىٰٓ أَرْبَعِينَ لَيْلَةً ثُمَّ ٱتَّخَذْتُمُ ٱلْعِجْلَ مِنۢ بَعْدِهِۦ وَأَنتُمْ ظَٰلِمُونَ","وَإِذْ نَجَّيْنَٰكُم مِّنْ ءَالِ فِرْعَوْنَ يَسُومُونَكُمْ سُوٓءَ ٱلْعَذَابِ يُذَبِّحُونَ أَبْنَآءَكُمْ وَيَسْتَحْيُونَ نِسَآءَكُمْ ۚ وَفِى ذَٰلِكُم بَلَآءٌ مِّن رَّبِّكُمْ عَظِيمٌ"]'::jsonb, 'وَإِذْ وَٰعَدْنَا مُوسَىٰٓ أَرْبَعِينَ لَيْلَةً ثُمَّ ٱتَّخَذْتُمُ ٱلْعِجْلَ مِنۢ بَعْدِهِۦ وَأَنتُمْ ظَٰلِمُونَ', true, 2);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('8f2c15b4-d680-4948-a086-83faea21e205', 1, 'A', 1, 'Lanjutkan potongan ayat', 21, 'multiple_choice', 'فَإِن لَّمْ تَفْعَلُوا۟ وَلَن تَفْعَلُوا۟ فَٱتَّقُوا۟ ٱلنَّارَ ٱلَّتِى وَقُودُهَا ٱلنَّاسُ وَٱلْحِجَارَةُ ۖ أُعِدَّتْ لِلْكَٰفِرِينَ', '["وَبَشِّرِ ٱلَّذِينَ ءَامَنُوا۟ وَعَمِلُوا۟ ٱلصَّٰلِحَٰتِ أَنَّ لَهُمْ جَنَّٰتٍ تَجْرِى مِن تَحْتِهَا ٱلْأَنْهَٰرُ ۖ كُلَّمَا رُزِقُوا۟ مِنْهَا مِن ثَمَرَةٍ رِّزْقًا ۙ قَالُوا۟ هَٰذَا ٱلَّذِى رُزِقْنَا مِن قَبْلُ ۖ وَأُتُوا۟ بِهِۦ مُتَشَٰبِهًا ۖ وَلَهُمْ فِيهَآ أَزْوَٰجٌ مُّطَهَّرَةٌ ۖ وَهُمْ فِيهَا خَٰلِدُونَ","وَإِن كُنتُمْ فِى رَيْبٍ مِّمَّا نَزَّلْنَا عَلَىٰ عَبْدِنَا فَأْتُوا۟ بِسُورَةٍ مِّن مِّثْلِهِۦ وَٱدْعُوا۟ شُهَدَآءَكُم مِّن دُونِ ٱللَّهِ إِن كُنتُمْ صَٰدِقِينَ"]'::jsonb, 'وَبَشِّرِ ٱلَّذِينَ ءَامَنُوا۟ وَعَمِلُوا۟ ٱلصَّٰلِحَٰتِ أَنَّ لَهُمْ جَنَّٰتٍ تَجْرِى مِن تَحْتِهَا ٱلْأَنْهَٰرُ ۖ كُلَّمَا رُزِقُوا۟ مِنْهَا مِن ثَمَرَةٍ رِّزْقًا ۙ قَالُوا۟ هَٰذَا ٱلَّذِى رُزِقْنَا مِن قَبْلُ ۖ وَأُتُوا۟ بِهِۦ مُتَشَٰبِهًا ۖ وَلَهُمْ فِيهَآ أَزْوَٰجٌ مُّطَهَّرَةٌ ۖ وَهُمْ فِيهَا خَٰلِدُونَ', true, 2);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('0a1769ac-9e5d-45cc-9e2d-da8291daeff8', 1, 'A', 1, 'Lanjutkan potongan ayat', 22, 'multiple_choice', 'يَٰٓأَيُّهَا ٱلنَّاسُ ٱعْبُدُوا۟ رَبَّكُمُ ٱلَّذِى خَلَقَكُمْ وَٱلَّذِينَ مِن قَبْلِكُمْ لَعَلَّكُمْ تَتَّقُونَ', '["ٱلَّذِى جَعَلَ لَكُمُ ٱلْأَرْضَ ذَلُولًا فَٱمْشُوا۟ فِى مَنَاكِبِهَا وَكُلُوا۟ مِن رِّزْقِهِۦ ۖ وَإِلَيْهِ ٱلنُّشُورُ","ٱلَّذِى جَعَلَ لَكُمُ ٱلْأَرْضَ فِرَٰشًا وَٱلسَّمَآءَ بِنَآءً وَأَنزَلَ مِنَ ٱلسَّمَآءِ مَآءً فَأَخْرَجَ بِهِۦ مِنَ ٱلثَّمَرَٰتِ رِزْقًا لَّكُمْ ۖ فَلَا تَجْعَلُوا۟ لِلَّهِ أَندَادًا وَأَنتُمْ تَعْلَمُونَ"]'::jsonb, 'ٱلَّذِى جَعَلَ لَكُمُ ٱلْأَرْضَ ذَلُولًا فَٱمْشُوا۟ فِى مَنَاكِبِهَا وَكُلُوا۟ مِن رِّزْقِهِۦ ۖ وَإِلَيْهِ ٱلنُّشُورُ', true, 2);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('6ae8be22-4daa-4d95-ac47-7a6e49ee6754', 1, 'A', 1, 'Lanjutkan potongan ayat', 23, 'multiple_choice', 'وَٱتَّقُوا۟ يَوْمًا لَّا تَجْزِى نَفْسٌ عَن نَّفْسٍ شَيْـًٔا وَلَا يُقْبَلُ مِنْهَا شَفَٰعَةٌ وَلَا يُؤْخَذُ مِنْهَا عَدْلٌ وَلَا هُمْ يُنصَرُونَ', '["وَإِذْ نَجَّيْنَٰكُم مِّنْ ءَالِ فِرْعَوْنَ يَسُومُونَكُمْ سُوٓءَ ٱلْعَذَابِ يُذَبِّحُونَ أَبْنَآءَكُمْ وَيَسْتَحْيُونَ نِسَآءَكُمْ ۚ وَفِى ذَٰلِكُم بَلَآءٌ مِّن رَّبِّكُمْ عَظِيمٌ","إِنَّ ٱلَّذِينَ ءَامَنُوا۟ وَٱلَّذِينَ هَادُوا۟ وَٱلنَّصَٰرَىٰ وَٱلصَّٰبِـِٔينَ مَنْ ءَامَنَ بِٱللَّهِ وَٱلْيَوْمِ ٱلْءَاخِرِ وَعَمِلَ صَٰلِحًا فَلَهُمْ أَجْرُهُمْ عِندَ رَبِّهِمْ وَلَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ"]'::jsonb, 'وَإِذْ نَجَّيْنَٰكُم مِّنْ ءَالِ فِرْعَوْنَ يَسُومُونَكُمْ سُوٓءَ ٱلْعَذَابِ يُذَبِّحُونَ أَبْنَآءَكُمْ وَيَسْتَحْيُونَ نِسَآءَكُمْ ۚ وَفِى ذَٰلِكُم بَلَآءٌ مِّن رَّبِّكُمْ عَظِيمٌ', true, 2);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('d3b97ea5-bfeb-4f53-a2ea-37df556a1791', 1, 'A', 1, 'Lanjutkan potongan ayat', 24, 'multiple_choice', 'هُوَ ٱلَّذِى خَلَقَ لَكُم مَّا فِى ٱلْأَرْضِ جَمِيعًا ثُمَّ ٱسْتَوَىٰٓ إِلَى ٱلسَّمَآءِ فَسَوَّىٰهُنَّ سَبْعَ سَمَٰوَٰتٍ ۚ وَهُوَ بِكُلِّ شَىْءٍ عَلِيمٌ', '["وَإِذْ نَجَّيْنَٰكُم مِّنْ ءَالِ فِرْعَوْنَ يَسُومُونَكُمْ سُوٓءَ ٱلْعَذَابِ يُذَبِّحُونَ أَبْنَآءَكُمْ وَيَسْتَحْيُونَ نِسَآءَكُمْ ۚ وَفِى ذَٰلِكُم بَلَآءٌ مِّن رَّبِّكُمْ عَظِيمٌ","وَإِذْ قَالَ رَبُّكَ لِلْمَلَٰٓئِكَةِ إِنِّى جَاعِلٌ فِى ٱلْأَرْضِ خَلِيفَةً ۖ قَالُوٓا۟ أَتَجْعَلُ فِيهَا مَن يُفْسِدُ فِيهَا وَيَسْفِكُ ٱلدِّمَآءَ وَنَحْنُ نُسَبِّحُ بِحَمْدِكَ وَنُقَدِّسُ لَكَ ۖ قَالَ إِنِّىٓ أَعْلَمُ مَا لَا تَعْلَمُونَ"]'::jsonb, 'وَإِذْ نَجَّيْنَٰكُم مِّنْ ءَالِ فِرْعَوْنَ يَسُومُونَكُمْ سُوٓءَ ٱلْعَذَابِ يُذَبِّحُونَ أَبْنَآءَكُمْ وَيَسْتَحْيُونَ نِسَآءَكُمْ ۚ وَفِى ذَٰلِكُم بَلَآءٌ مِّن رَّبِّكُمْ عَظِيمٌ', true, 2);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('6b0c9ca6-ce03-4b21-a506-07fe768b0ef2', 1, 'A', 1, 'Lanjutkan potongan ayat', 25, 'multiple_choice', 'ٱلَّذِى جَعَلَ لَكُمُ ٱلْأَرْضَ فِرَٰشًا وَٱلسَّمَآءَ بِنَآءً وَأَنزَلَ مِنَ ٱلسَّمَآءِ مَآءً فَأَخْرَجَ بِهِۦ مِنَ ٱلثَّمَرَٰتِ رِزْقًا لَّكُمْ ۖ فَلَا تَجْعَلُوا۟ لِلَّهِ أَندَادًا وَأَنتُمْ', '["يَعْلَمُونَ","تَعْلَمُونَ"]'::jsonb, 'يَعْلَمُونَ', true, 2);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('e9bbab07-a533-429d-b4d4-08e0b348c7bf', 1, 'A', 1, 'Lanjutkan potongan ayat', 26, 'multiple_choice', 'خَتَمَ ٱللَّهُ عَلَىٰ قُلُوبِهِمْ وَعَلَىٰ سَمْعِهِمْ ۖ وَعَلَىٰٓ أَبْصَٰرِهِمْ غِشَٰوَةٌ ۖ وَلَهُمْ', '["عَذَابٌ أَلِيمٌ","عَذَابٌ عَظِيمٌ"]'::jsonb, 'عَذَابٌ أَلِيمٌ', true, 2);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('c51f6604-cb86-4ff5-9fed-332c2690b339', 1, 'A', 1, 'Lanjutkan potongan ayat', 27, 'multiple_choice', 'خَتَمَ ٱللَّهُ عَلَىٰ قُلُوبِهِمْ وَعَلَىٰ سَمْعِهِمْ ۖ وَعَلَىٰٓ أَبْصَٰرِهِمْ غِشَٰوَةٌ ۖ وَلَهُمْ يَٰبَنِىٓ إِسْرَٰٓءِيلَ ٱذْكُرُوا۟ نِعْمَتِىَ ٱلَّتِىٓ أَنْعَمْتُ عَلَيْكُمْ وَأَوْفُوا۟ بِعَهْدِىٓ أُوفِ بِعَهْدِكُمْ', '["وَإِيَّٰىَ فَٱتَّقُونِ","وَإِيَّٰىَ فَٱرْهَبُونِ"]'::jsonb, 'وَإِيَّٰىَ فَٱتَّقُونِ', true, 2);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('60e6e478-1d77-46f1-b661-c796eb20ba69', 1, 'A', 1, 'Lanjutkan potongan ayat', 28, 'multiple_choice', 'خَتَمَ ٱللَّهُ عَلَىٰ قُلُوبِهِمْ وَعَلَىٰ سَمْعِهِمْ ۖ وَعَلَىٰٓ أَبْصَٰرِهِمْ غِشَٰوَةٌ ۖ وَلَهُمْ يَٰبَنِىٓ إِسْرَٰٓءِيلَ ٱذْكُرُوا۟ نِعْمَتِىَ ٱلَّتِىٓ أَنْعَمْتُ عَلَيْكُمْ وَأَوْفُوا۟ بِعَهْدِىٓ أُوفِ بِعَهْدِكُمْ', '["وَإِيَّٰىَ فَٱتَّقُونِ","وَإِيَّٰىَ فَٱرْهَبُونِ"]'::jsonb, 'وَإِيَّٰىَ فَٱتَّقُونِ', true, 2);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('6e8eee99-4922-48ca-aa17-5e59a3d6b32b', 1, 'A', 1, 'Lanjutkan potongan ayat', 29, 'multiple_choice', 'وَلَا تَلْبِسُوا۟ ٱلْحَقَّ بِٱلْبَٰطِلِ وَتَكْتُمُوا۟ ٱلْحَقَّ وَأَنتُمْ', '["تَعْلَمُونَ","تَعْقِلُونَ"]'::jsonb, 'تَعْلَمُونَ', true, 2);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('4bc19974-53bd-45f6-92ce-36807e16dce2', 1, 'A', 1, 'Lanjutkan potongan ayat', 30, 'multiple_choice', 'أَتَأْمُرُونَ ٱلنَّاسَ بِٱلْبِرِّ وَتَنسَوْنَ أَنفُسَكُمْ وَأَنتُمْ تَتْلُونَ ٱلْكِتَٰبَ ۚ أَفَلَا تَعْقِلُونَ', '["تَنظُرُونَ","تَعْقِلُونَ"]'::jsonb, 'تَنظُرُونَ', true, 2);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('d8aafe24-cb18-4b30-b1eb-f8df1c623a50', 1, 'A', 1, 'Lanjutkan potongan ayat', 31, 'multiple_choice', 'هُوَ ٱلَّذِى خَلَقَ لَكُم مَّا فِى ٱلْأَرْضِ جَمِيعًا ثُمَّ ٱسْتَوَىٰٓ إِلَى ٱلسَّمَآءِ فَسَوَّىٰهُنَّ سَبْعَ سَمَٰوَٰتٍ ۚ وَهُوَ بِكُلِّ شَىْءٍ عَلِيمٌ', '["وَإِذْ قَالَ رَبُّكَ لِلْمَلَٰٓئِكَةِ إِنِّى جَاعِلٌ فِى ٱلْأَرْضِ خَلِيفَةً ۖ قَالُوٓا۟ أَتَجْعَلُ فِيهَا مَن يُفْسِدُ فِيهَا وَيَسْفِكُ ٱلدِّمَآءَ وَنَحْنُ نُسَبِّحُ بِحَمْدِكَ وَنُقَدِّسُ لَكَ ۖ قَالَ إِنِّىٓ أَعْلَمُ مَا لَا تَعْلَمُونَ","وَإِذْ نَجَّيْنَٰكُم مِّنْ ءَالِ فِرْعَوْنَ يَسُومُونَكُمْ سُوٓءَ ٱلْعَذَابِ يُذَبِّحُونَ أَبْنَآءَكُمْ وَيَسْتَحْيُونَ نِسَآءَكُمْ ۚ وَفِى ذَٰلِكُم بَلَآءٌ مِّن رَّبِّكُمْ عَظِيمٌ"]'::jsonb, 'وَإِذْ قَالَ رَبُّكَ لِلْمَلَٰٓئِكَةِ إِنِّى جَاعِلٌ فِى ٱلْأَرْضِ خَلِيفَةً ۖ قَالُوٓا۟ أَتَجْعَلُ فِيهَا مَن يُفْسِدُ فِيهَا وَيَسْفِكُ ٱلدِّمَآءَ وَنَحْنُ نُسَبِّحُ بِحَمْدِكَ وَنُقَدِّسُ لَكَ ۖ قَالَ إِنِّىٓ أَعْلَمُ مَا لَا تَعْلَمُونَ', true, 2);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('b6a27abd-70d6-4420-9992-6d05b6793b89', 1, 'A', 1, 'Lanjutkan potongan ayat', 32, 'multiple_choice', 'فَتَلَقَّىٰٓ ءَادَمُ مِن رَّبِّهِۦ كَلِمَٰتٍ فَتَابَ عَلَيْهِ ۚ إِنَّهُۥ هُوَ ٱلتَّوَّابُ ٱلرَّحِيمُ', '["قُلْنَا ٱهْبِطُوا۟ مِنْهَا جَمِيعًا ۖ فَإِمَّا يَأْتِيَنَّكُم مِّنِّى هُدًى فَمَن تَبِعَ هُدَاىَ فَلَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ","وَإِذْ قُلْنَا ٱدْخُلُوا۟ هَٰذِهِ ٱلْقَرْيَةَ فَكُلُوا۟ مِنْهَا حَيْثُ شِئْتُمْ رَغَدًا وَٱدْخُلُوا۟ ٱلْبَابَ سُجَّدًا وَقُولُوا۟ حِطَّةٌ نَّغْفِرْ لَكُمْ خَطَٰيَٰكُمْ ۚ وَسَنَزِيدُ ٱلْمُحْسِنِينَ"]'::jsonb, 'قُلْنَا ٱهْبِطُوا۟ مِنْهَا جَمِيعًا ۖ فَإِمَّا يَأْتِيَنَّكُم مِّنِّى هُدًى فَمَن تَبِعَ هُدَاىَ فَلَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ', true, 2);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('ce624a98-9f59-45ac-b691-3d7ebc2d3700', 1, 'A', 1, 'Lanjutkan potongan ayat', 33, 'multiple_choice', 'وَمِنْهُمْ أُمِّيُّونَ لَا يَعْلَمُونَ ٱلْكِتَٰبَ إِلَّآ أَمَانِىَّ وَإِنْ هُمْ إِلَّا يَظُنُّونَ', '["وَإِذْ أَخَذْنَا مِيثَٰقَكُمْ وَرَفَعْنَا فَوْقَكُمُ ٱلطُّورَ خُذُوا۟ مَآ ءَاتَيْنَٰكُم بِقُوَّةٍ وَٱذْكُرُوا۟ مَا فِيهِ لَعَلَّكُمْ تَتَّقُونَ","فَوَيْلٌ لِّلَّذِينَ يَكْتُبُونَ ٱلْكِتَٰبَ بِأَيْدِيهِمْ ثُمَّ يَقُولُونَ هَٰذَا مِنْ عِندِ ٱللَّهِ لِيَشْتَرُوا۟ بِهِۦ ثَمَنًا قَلِيلًا ۖ فَوَيْلٌ لَّهُم مِّمَّا كَتَبَتْ أَيْدِيهِمْ وَوَيْلٌ لَّهُم مِّمَّا يَكْسِبُونَ","فَوَيْلٌ لِّلَّذِينَ يَكْتُبُونَ ٱلْكِتَٰبَ بِأَيْدِيهِمْ ثُمَّ يَقُولُونَ هَٰذَا مِنْ عِندِ ٱللَّهِ لِيَشْتَرُوا۟ بِهِۦ ثَمَنًا قَلِيلًا ۖ فَوَيْلٌ لَّهُم مِّمَّا كَتَبَتْ أَيْدِيهِمْ وَوَيْلٌ لَّهُم مِّمَّا يَكْسِبُونَ"]'::jsonb, 'وَإِذْ أَخَذْنَا مِيثَٰقَكُمْ وَرَفَعْنَا فَوْقَكُمُ ٱلطُّورَ خُذُوا۟ مَآ ءَاتَيْنَٰكُم بِقُوَّةٍ وَٱذْكُرُوا۟ مَا فِيهِ لَعَلَّكُمْ تَتَّقُونَ', true, 2);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('3b011e49-eb91-4ecf-b1d3-40bfa643581f', 1, 'A', 1, 'Lanjutkan potongan ayat', 34, 'multiple_choice', 'وَإِذْ وَٰعَدْنَا مُوسَىٰٓ أَرْبَعِينَ لَيْلَةً ثُمَّ ٱتَّخَذْتُمُ ٱلْعِجْلَ مِنۢ بَعْدِهِۦ وَأَنتُمْ ظَٰلِمُونَ', '["وَإِذْ ءَاتَيْنَا مُوسَى ٱلْكِتَٰبَ وَٱلْفُرْقَانَ لَعَلَّكُمْ تَهْتَدُونَ","ثُمَّ عَفَوْنَا عَنكُم مِّنۢ بَعْدِ ذَٰلِكَ لَعَلَّكُمْ تَشْكُرُونَ"]'::jsonb, 'وَإِذْ ءَاتَيْنَا مُوسَى ٱلْكِتَٰبَ وَٱلْفُرْقَانَ لَعَلَّكُمْ تَهْتَدُونَ', true, 2);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('364cb377-8067-48e7-a29e-da943e3c9d27', 1, 'A', 2, 'Tebak halaman', 35, 'multiple_choice', 'بَلَىٰ مَن كَسَبَ سَيِّئَةً وَأَحَٰطَتْ بِهِۦ خَطِيٓـَٔتُهُۥ فَأُو۟لَٰٓئِكَ أَصْحَٰبُ ٱلنَّارِ ۖ هُمْ فِيهَا خَٰلِدُونَTerdapat pada halaman', '["Halaman 10","Halaman 9","Halaman 8","Halaman 7"]'::jsonb, 'Halaman 10', true, 1);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('36289e62-e5df-4972-a348-480f6663b685', 1, 'A', 2, 'Tebak halaman', 36, 'multiple_choice', 'وَإِذْ قَتَلْتُمْ نَفْسًا فَٱدَّٰرَْٰٔتُمْ فِيهَا ۖ وَٱللَّهُ مُخْرِجٌ مَّا كُنتُمْ تَكْتُمُونَTerdapat pada halaman', '["Halaman 10","Halaman 9","Halaman 8","Halaman 7"]'::jsonb, 'Halaman 10', true, 1);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('06ff0849-3bd9-4c16-bb29-8e820795f113', 1, 'A', 2, 'Tebak halaman', 37, 'multiple_choice', 'فَبَدَّلَ ٱلَّذِينَ ظَلَمُوا۟ قَوْلًا غَيْرَ ٱلَّذِى قِيلَ لَهُمْ فَأَنزَلْنَا عَلَى ٱلَّذِينَ ظَلَمُوا۟ رِجْزًا مِّنَ ٱلسَّمَآءِ بِمَا كَانُوا۟ يَفْسُقُونَTerdapat pada halaman', '["Halaman 10","Halaman 9","Halaman 8","Halaman 7"]'::jsonb, 'Halaman 10', true, 1);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('3dda1048-2404-4b5b-94fd-04caf1f37913', 1, 'A', 2, 'Tebak halaman', 38, 'multiple_choice', 'وَإِذْ أَخَذْنَا مِيثَٰقَكُمْ وَرَفَعْنَا فَوْقَكُمُ ٱلطُّورَ خُذُوا۟ مَآ ءَاتَيْنَٰكُم بِقُوَّةٍ وَٱذْكُرُوا۟ مَا فِيهِ لَعَلَّكُمْ تَتَّقُونَTerdapat pada halaman', '["Halaman 10","Halaman 9","Halaman 8","Halaman 7"]'::jsonb, 'Halaman 10', true, 1);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('9018dac6-de18-4513-8dbc-024875774f5d', 1, 'A', 2, 'Tebak halaman', 39, 'multiple_choice', 'وَإِذْ قُلْنَا ٱدْخُلُوا۟ هَٰذِهِ ٱلْقَرْيَةَ فَكُلُوا۟ مِنْهَا حَيْثُ شِئْتُمْ رَغَدًا وَٱدْخُلُوا۟ ٱلْبَابَ سُجَّدًا وَقُولُوا۟ حِطَّةٌ نَّغْفِرْ لَكُمْ خَطَٰيَٰكُمْ ۚ وَسَنَزِيدُ ٱلْمُحْسِنِينَTerdapat pada halaman', '["Halaman 10","Halaman 9","Halaman 8","Halaman 7"]'::jsonb, 'Halaman 10', true, 1);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('40089541-7750-4a1e-b337-19577934e685', 1, 'A', 2, 'Tebak halaman', 40, 'multiple_choice', 'وَإِذَا لَقُوا۟ ٱلَّذِينَ ءَامَنُوا۟ قَالُوٓا۟ ءَامَنَّا وَإِذَا خَلَا بَعْضُهُمْ إِلَىٰ بَعْضٍ قَالُوٓا۟ أَتُحَدِّثُونَهُم بِمَا فَتَحَ ٱللَّهُ عَلَيْكُمْ لِيُحَآجُّوكُم بِهِۦ عِندَ رَبِّكُمْ ۚ أَفَلَا تَعْقِلُونَTerdapat pada halaman', '["Halaman 10","Halaman 9","Halaman 8","Halaman 7"]'::jsonb, 'Halaman 10', true, 1);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('9aa874e0-0187-4e94-850e-44e88eded887', 1, 'A', 2, 'Tebak halaman', 41, 'multiple_choice', 'وَقَالُوا۟ لَن تَمَسَّنَا ٱلنَّارُ إِلَّآ أَيَّامًا مَّعْدُودَةً ۚ قُلْ أَتَّخَذْتُمْ عِندَ ٱللَّهِ عَهْدًا فَلَن يُخْلِفَ ٱللَّهُ عَهْدَهُۥٓ ۖ أَمْ تَقُولُونَ عَلَى ٱللَّهِ مَا لَا تَعْلَمُونَTerdapat pada halaman', '["Halaman 10","Halaman 9","Halaman 8","Halaman 7"]'::jsonb, 'Halaman 10', true, 1);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('8b87e272-7277-4742-a7de-ffb5d3de90be', 1, 'A', 2, 'Tebak halaman', 42, 'multiple_choice', 'قَالُوا۟ ٱدْعُ لَنَا رَبَّكَ يُبَيِّن لَّنَا مَا هِىَ ۚ قَالَ إِنَّهُۥ يَقُولُ إِنَّهَا بَقَرَةٌ لَّا فَارِضٌ وَلَا بِكْرٌ عَوَانٌۢ بَيْنَ ذَٰلِكَ ۖ فَٱفْعَلُوا۟ مَا تُؤْمَرُونَTerdapat pada halaman', '["Halaman 10","Halaman 9","Halaman 8","Halaman 7"]'::jsonb, 'Halaman 10', true, 1);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('cb398f55-edb8-46e1-820e-00bde0b1faf0', 1, 'A', 2, 'Tebak halaman', 43, 'multiple_choice', 'أُو۟لَٰٓئِكَ ٱلَّذِينَ ٱشْتَرَوُا۟ ٱلضَّلَٰلَةَ بِٱلْهُدَىٰ فَمَا رَبِحَت تِّجَٰرَتُهُمْ وَمَا كَانُوا۟ مُهْتَدِينَTerdapat pada halaman', '["Halaman 6","Halaman 5","Halaman 4","Halaman 3","Halaman 2","Halaman 1"]'::jsonb, 'Halaman 6', true, 1);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('5aa8503d-d394-427a-b623-51be8807c5e0', 1, 'A', 2, 'Tebak halaman', 44, 'multiple_choice', 'وَإِذْ قُلْنَا لِلْمَلَٰٓئِكَةِ ٱسْجُدُوا۟ لِءَادَمَ فَسَجَدُوٓا۟ إِلَّآ إِبْلِيسَ أَبَىٰ وَٱسْتَكْبَرَ وَكَانَ مِنَ ٱلْكَٰفِرِينَTerdapat pada halaman', '["Halaman 6","Halaman 5","Halaman 4","Halaman 3","Halaman 2","Halaman 1"]'::jsonb, 'Halaman 6', true, 1);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('42d65869-ab01-427f-b1a5-9c9d3c499b2f', 1, 'A', 2, 'Tebak halaman', 45, 'multiple_choice', 'إِنَّ ٱللَّهَ لَا يَسْتَحْىِۦٓ أَن يَضْرِبَ مَثَلًا مَّا بَعُوضَةً فَمَا فَوْقَهَا ۚ فَأَمَّا ٱلَّذِينَ ءَامَنُوا۟ فَيَعْلَمُونَ أَنَّهُ ٱلْحَقُّ مِن رَّبِّهِمْ ۖ وَأَمَّا ٱلَّذِينَ كَفَرُوا۟ فَيَقُولُونَ مَاذَآ أَرَادَ ٱللَّهُ بِهَٰذَا مَثَلًا ۘ يُضِلُّ بِهِۦ كَثِيرًا وَيَهْدِى بِهِۦ كَثِيرًا ۚ وَمَا يُضِلُّ بِهِۦٓ إِلَّا ٱلْفَٰسِقِينَTerdapat pada halaman', '["Halaman 6","Halaman 5","Halaman 4","Halaman 3","Halaman 2","Halaman 1"]'::jsonb, 'Halaman 6', true, 1);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('f0b56e68-50b8-4b57-8d81-0e1479cfc7bb', 1, 'A', 2, 'Tebak halaman', 46, 'multiple_choice', 'كَيْفَ تَكْفُرُونَ بِٱللَّهِ وَكُنتُمْ أَمْوَٰتًا فَأَحْيَٰكُمْ ۖ ثُمَّ يُمِيتُكُمْ ثُمَّ يُحْيِيكُمْ ثُمَّ إِلَيْهِ تُرْجَعُونَTerdapat pada halaman', '["Halaman 6","Halaman 5","Halaman 4","Halaman 3","Halaman 2","Halaman 1"]'::jsonb, 'Halaman 6', true, 1);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('1f17f3ba-0661-4e7c-9f87-f9710c959f0e', 1, 'A', 2, 'Tebak halaman', 47, 'multiple_choice', 'ثُمَّ عَفَوْنَا عَنكُم مِّنۢ بَعْدِ ذَٰلِكَ لَعَلَّكُمْ تَشْكُرُونَTerdapat pada halaman', '["Halaman 6","Halaman 5","Halaman 4","Halaman 3","Halaman 2","Halaman 1"]'::jsonb, 'Halaman 6', true, 1);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('103031a3-9ac1-4546-aba6-2ccb5c4c63b5', 1, 'A', 2, 'Tebak halaman', 48, 'multiple_choice', 'وَأَقِيمُوا۟ ٱلصَّلَوٰةَ وَءَاتُوا۟ ٱلزَّكَوٰةَ وَٱرْكَعُوا۟ مَعَ ٱلرَّٰكِعِينَTerdapat pada halaman', '["Halaman 6","Halaman 5","Halaman 4","Halaman 3","Halaman 2","Halaman 1"]'::jsonb, 'Halaman 6', true, 1);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('9bbeb138-d357-4b0b-b751-0f8e97e4a41b', 1, 'A', 2, 'Tebak halaman', 49, 'multiple_choice', 'يَٰبَنِىٓ إِسْرَٰٓءِيلَ ٱذْكُرُوا۟ نِعْمَتِىَ ٱلَّتِىٓ أَنْعَمْتُ عَلَيْكُمْ وَأَوْفُوا۟ بِعَهْدِىٓ أُوفِ بِعَهْدِكُمْ وَإِيَّٰىَ فَٱرْهَبُونِTerdapat pada halaman', '["Halaman 6","Halaman 5","Halaman 4","Halaman 3","Halaman 2","Halaman 1"]'::jsonb, 'Halaman 6', true, 1);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('37ab3cfc-b121-4754-9d1b-d8e5d0fa086c', 1, 'A', 2, 'Tebak halaman', 50, 'multiple_choice', 'وَلَا تَلْبِسُوا۟ ٱلْحَقَّ بِٱلْبَٰطِلِ وَتَكْتُمُوا۟ ٱلْحَقَّ وَأَنتُمْ تَعْلَمُونَTerdapat pada halaman', '["Halaman 6","Halaman 5","Halaman 4","Halaman 3","Halaman 2","Halaman 1"]'::jsonb, 'Halaman 6', true, 1);
INSERT INTO public.exam_questions (id, juz_number, question_package, section_number, section_title, question_number, question_type, question_text, options, correct_answer, is_active, points)
VALUES ('45a9201a-bf3b-4091-9cd1-b9344dd6ab43', 1, 'A', 2, 'Tebak halaman', 51, 'multiple_choice', 'وَظَلَّلْنَا عَلَيْكُمُ ٱلْغَمَامَ وَأَنزَلْنَا عَلَيْكُمُ ٱلْمَنَّ وَٱلسَّلْوَىٰ ۖ كُلُوا۟ مِن طَيِّبَٰتِ مَا رَزَقْنَٰكُمْ ۖ وَمَا ظَلَمُونَا وَلَٰكِن كَانُوٓا۟ أَنفُسَهُمْ يَظْلِمُونَTerdapat pada halaman', '["Halaman 6","Halaman 5","Halaman 4","Halaman 3","Halaman 2","Halaman 1"]'::jsonb, 'Halaman 6', true, 1);
COMMIT;